# Configurations
title:            ICHEC Quiz
longtitle:        ICHEC Web Quiz setup
author:           ICHEC Quantum Team
email:            qpcc@ichec.ie
description: >
  ICHEC lecture notes, quizes

version:          3.9
gitbook_version:  3.2.3

relative_url: true
#url:              'https://sighingnow.github.io'
#baseurl:          '/jekyll-gitbook'
baseurl:          '/quiz'
rss:              RSS

# bootstrap: use the remote theme for the site itself
#remote_theme: sighingnow/jekyll-gitbook

markdown_ext:             md
#, markdown,mkdown,mkdn,mkd,

toc:
  enabled: true
  h_min: 1
  h_max: 4

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

toc:
  enabled: true

# Permalinks
# permalink:                /:categories/:year-:month-:day-:title:output_ext
# permalink:                /:slugified_categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts
  - scratch

#include:
#  - qpcc
#  - pyqm
#  - gitbook.md

#collections:
#  pages:
#    output: true
#    permalink: /:collection/:path/

page_width: 1200px

destination:      ./_site
#incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-relative-links
  - jemoji
  - jekyll-toc
  - jekyll-youtube


syntax_highlighter_style: colorful
highlighter: coderay